package com.leo.sport.domain;

import java.io.Serializable;
import java.util.Date;

public class User extends Model implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ucode
     *
     * @mbggenerated
     */
    private String ucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login
     *
     * @mbggenerated
     */
    private String login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.isort
     *
     * @mbggenerated
     */
    private Integer isort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.islock
     *
     * @mbggenerated
     */
    private String islock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.rcdtime
     *
     * @mbggenerated
     */
    private Date rcdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.role
     *
     * @mbggenerated
     */
    private String role;
    private String roleName;
    private String categoryName;//用户类型名称
    
    public String getRoleName() {
		return roleName;
	}
    
    private String authData;//权限数据
    private Integer authorityType;//权限类型

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ucode
     *
     * @return the value of sys_user.ucode
     *
     * @mbggenerated
     */
    public String getUcode() {
        return ucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ucode
     *
     * @param ucode the value for sys_user.ucode
     *
     * @mbggenerated
     */
    public void setUcode(String ucode) {
        this.ucode = ucode == null ? null : ucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.uname
     *
     * @return the value of sys_user.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.uname
     *
     * @param uname the value for sys_user.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login
     *
     * @return the value of sys_user.login
     *
     * @mbggenerated
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login
     *
     * @param login the value for sys_user.login
     *
     * @mbggenerated
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.category
     *
     * @return the value of sys_user.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.category
     *
     * @param category the value for sys_user.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.pwd
     *
     * @return the value of sys_user.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.pwd
     *
     * @param pwd the value for sys_user.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.isort
     *
     * @return the value of sys_user.isort
     *
     * @mbggenerated
     */
    public Integer getIsort() {
        return isort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.isort
     *
     * @param isort the value for sys_user.isort
     *
     * @mbggenerated
     */
    public void setIsort(Integer isort) {
        this.isort = isort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.flag
     *
     * @return the value of sys_user.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.flag
     *
     * @param flag the value for sys_user.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.memo
     *
     * @return the value of sys_user.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.memo
     *
     * @param memo the value for sys_user.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.islock
     *
     * @return the value of sys_user.islock
     *
     * @mbggenerated
     */
    public String getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.islock
     *
     * @param islock the value for sys_user.islock
     *
     * @mbggenerated
     */
    public void setIslock(String islock) {
        this.islock = islock == null ? null : islock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.rcdtime
     *
     * @return the value of sys_user.rcdtime
     *
     * @mbggenerated
     */
    public Date getRcdtime() {
        return rcdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.rcdtime
     *
     * @param rcdtime the value for sys_user.rcdtime
     *
     * @mbggenerated
     */
    public void setRcdtime(Date rcdtime) {
        this.rcdtime = rcdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.role
     *
     * @return the value of sys_user.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.role
     *
     * @param role the value for sys_user.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
    
    private String inputCode;
    private String checkCode;

	public String getInputCode() {
		return inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getCheckCode() {
		return checkCode;
	}

	public void setCheckCode(String checkCode) {
		this.checkCode = checkCode;
	}
    private String comCode;//所在小区编号

    private String comName;
    
    
	public String getComName() {
		return comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getAuthData() {
		return authData;
	}

	public void setAuthData(String authData) {
		this.authData = authData;
	}

	public Integer getAuthorityType() {
		return authorityType;
	}

	public void setAuthorityType(Integer authorityType) {
		this.authorityType = authorityType;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
}